# ===============================================================================
# OpenRevLoader Configuration File (DO NOT USE IT ON CLASSIC revLoader.exe!!=
# ===============================================================================

[Loader]
# Executable name or relative path of the target game
ProcName=hl2.exe

# Default command line arguments passed to the game
# (Example for TF2: -game tf | Garry's Mod: -game garrysmod)
ProcArgs=-game tf -steam -novid -console

# Steam Client emulation DLL file to be loaded
SteamClientDll=steamclient.dll

# Steam Overlay DLL to automatically inject into the target process. ITS REALLY W.I.P.
# (It's optional. if you don't want the overlay or you don't have the DLL, u can just comment out with a semicolon ';' at the start of the line to disable)
OverlayDLL=GameOverlayRenderer.dll


[Steam]
# Steam AppID of the target game
# 440   = Team Fortress 2
# 4000  = Garry's Mod
# 240   = Counter-Strike: Source
# 220   = Half-Life 2
AppId=440


[Emulator]
# Your in-game username (Name visible on scoreboards)
PlayerName=Player

# In-game language selection (english, turkish, german, russian, etc.)
Language=english

# SteamID generation method:
# 1 = Hardware-based (HWID) static SteamID generation (Recommended)
# 2 = IP address-based SteamID generation
# 3 = Random SteamID generation on every launch
SteamIDBy=1

# Enable logging/debug mode (0 = Disabled, 1 = Enabled)
Logging=0
